#!/usr/bin/env python3
"""
export.py — Export domain memories from an MCP Memory Server database for AgentCommons submission.

Extracts domain-scoped memories by tag, strips all identity fields,
and produces a submission-ready dataset folder.

Usage:
  python export.py --db ./memory.db --tags cloudflare,workers --out ./my-dataset
  python export.py --db ./memory.db --tags kubernetes --out ./k8s-dataset --name k8s-patterns
"""

import argparse
import json
import shutil
import sqlite3
from datetime import date
from pathlib import Path

# Tags that indicate personal/interpersonal content — never exportable
BLOCKED_TAGS = {"personality", "relationship", "style", "personal", "private"}


def export_dataset(db_path: Path, tags: list[str], out_path: Path, name: str) -> None:
    if not db_path.exists():
        print(f"Error: database not found at {db_path}")
        return

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    # Fetch domain-only memories matching the requested tags
    filter_tags = set(tags)
    all_memories = conn.execute(
        "SELECT id, content, embedding, tags, created_at FROM memories WHERE scope IN ('agent', 'team')"
    ).fetchall()
    conn.close()

    exportable = []
    for row in all_memories:
        memory_tags = set(json.loads(row["tags"]))
        # Block if any personal tags present
        if memory_tags & BLOCKED_TAGS:
            continue
        # Include if any requested tags match (or export all domain memories if no tags specified)
        if not filter_tags or (memory_tags & filter_tags):
            exportable.append(row)

    if not exportable:
        print(f"No exportable memories found matching tags: {tags}")
        print("Check that memories exist with those tags and are not blocked by personal tag rules.")
        return

    # Create output directory
    out_path.mkdir(parents=True, exist_ok=True)
    db_out = out_path / "knowledge.db"

    # Build the export database — identical schema, identity stripped
    export_conn = sqlite3.connect(db_out)
    export_conn.executescript("""
        CREATE TABLE IF NOT EXISTS memories (
            id        TEXT PRIMARY KEY,
            content   TEXT NOT NULL,
            embedding TEXT NOT NULL,
            tags      TEXT NOT NULL DEFAULT '[]',
            source_at TEXT NOT NULL
        );
    """)

    for row in exportable:
        export_conn.execute(
            "INSERT OR IGNORE INTO memories (id, content, embedding, tags, source_at) VALUES (?, ?, ?, ?, ?)",
            (row["id"], row["content"], row["embedding"], row["tags"], row["created_at"])
        )

    export_conn.commit()
    export_conn.close()

    # Detect embedding model from the MCP server config if available
    embedding_model = "nomic-embed-text"
    mcp_server_env = db_path.parent / ".env"
    # (future: read from config — defaulting to nomic-embed-text for now)

    # Write metadata
    metadata = {
        "name": name,
        "version": "1.0.0",
        "embedding_model": embedding_model,
        "topic_tags": tags,
        "agent_type": "engineering",
        "record_count": len(exportable),
        "language": "en",
        "submitted_by": "your-github-username",
        "submitted_at": date.today().isoformat(),
        "provenance": [],
        "description": f"Domain knowledge dataset covering: {', '.join(tags)}. Generated by an AI agent via MCP Memory Server."
    }

    (out_path / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")

    # Copy README template
    template_readme = Path(__file__).parent.parent / "submissions" / ".template" / "README.md"
    if template_readme.exists():
        shutil.copy(template_readme, out_path / "README.md")
    else:
        (out_path / "README.md").write_text(f"# {name}\n\nFill in dataset description.\n")

    print(f"Export complete.")
    print(f"  Records exported: {len(exportable)}")
    print(f"  Output:           {out_path}/")
    print(f"")
    print(f"Next steps:")
    print(f"  1. Review {out_path}/knowledge.db for any sensitive content")
    print(f"  2. Fill in {out_path}/metadata.json (submitted_by, description)")
    print(f"  3. Fill in {out_path}/README.md")
    print(f"  4. Run: python validate.py --dataset {out_path}")
    print(f"  5. Submit via Pull Request to community/<topic>/{name}/")


def main():
    parser = argparse.ArgumentParser(description="Export domain memories for AgentCommons submission.")
    parser.add_argument("--db",   required=True, help="Path to memory.db")
    parser.add_argument("--tags", required=True, help="Comma-separated topic tags to export")
    parser.add_argument("--out",  required=True, help="Output directory for the dataset")
    parser.add_argument("--name", default=None,  help="Dataset name (defaults to tags joined by dashes)")
    args = parser.parse_args()

    tags = [t.strip() for t in args.tags.split(",")]
    name = args.name or "-".join(tags)
    export_dataset(Path(args.db), tags, Path(args.out), name)


if __name__ == "__main__":
    main()
